### ISSUE TITLE
Publish to F-Droid

### ISSUE THREAD

**Issue by jomo** [gentlecat/Simple-Counter#36]
Thanks for this simple (but very nice looking) app!

Since it's open source, would you consider publishing it to [F-Droid](https://f-droid.org/) (a Free and Open Source alternative to the Google Play Store)?

The existing alternatives on F-Droid are either old and ugly as :shit: or can't save counts :/

**Comment by gentlecat** [comment]
Sure, I'll try to look into that. Thanks for suggestion!

**Comment by gentlecat** [comment]
I submitted it on their forum: https://f-droid.org/forums/topic/simple-counter/. You can track progress there too.

**Comment by jomo** [comment]
awesome, thank you! :+1:

**Comment by gentlecat** [comment]
Should be available now.
